version: 2
jobs:
  build:
    docker:
      - image: haskell:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache
      - run: apt-get update && apt-get install -y postgresql
      - run: stack build
      - run: stack test
      - run: stack haddock
      - save_cache:
          key: dependency-cache
          paths:
            - ".stack-work"
